# 2022-04-21

### Today I Learned

- Promise
- async/await
- try/catch

#### Promise

---

- 설명

  `Promise`는 프로미스가 생성된 시점에는 알려지지 않았을 수도 있는 값을 위한 대리자로, 비동기 연산이 종료된 이후에 결과 값과 실패 사유를 처리하기 위한 처리기를 연결할 수 있다. (`then()`, `catch()`)

  프로미스를 사용하면 비동기 메서드에서 마치 동기 메서드처럼 값을 반환할 수 있다. 다만 최종 결과를 반환하는 것이 아니고, 미래의 어떤 시점에 결과를 제공하겠다는 '약속'(프로미스)을 반환다.
  [출처] MDN 

- Promise의 3가지 상태

  - Pending : 비동기 처리 로직이 아직 완료되지 않은 상태
  - Fulfilled : 비동기 처리가 완료되어 프로미스 결과 값을 반환해준 상태
  - Rejected :  비동기 처리가 실패하거나 오류가 발생한 상태

- Pending

  ```javascript
  new Promise();
  ```

  위와 같이  `new Promise();`  메서드를 호출하면 **대기** 상태가 된다.

   `new Promise();`  메서드를 호출할 때 콜백 함수를 선언할 수 있고, 콜백 함수의 인자는 `resolve()`,`reject()` 이다. 

- Fulfilled 
  `reslove`를 아래와 같이 실행하면 **이행** 상태가 된다.

  ```javascript
  new Promise(function(resolve, reject) {
  	reslove();
  });
  ```

  이행 상태가 되면 `.then()`을 이용하여 처리 결과 값을 받을 수 있다.

  - reslove() 는 주어진 값으로 이행하는 `Promise`  객체를 반환한다.
    이때 `.then()`을 활용하면 `Prmosie` 객체는 `.then()`을 따라가서 자신의 최종 상태를 결정한다고 한다. 

    - `.then()`을 따라가는 예제 코드

      ```javascript
      passport.deserializeUser((id, done) => {
            User.findOne({
              where: { id }
            })
            .then(user => done(null, user))
            .catch(err => done(err));
          });
      ```

- Rejected
  앞서 `new Promise()`로 프로미스 객체를 생성하면 콜백 함수 인자로 `resolve`와 `reject`를 사용할 수 있다하였는데 `reject()`를 호출하면 **실패** 상태가 된다.

  그리고 실패 상태가 되면 실패한 이유를 `catch()`로 받을 수 있다.



> - Promise 함수 판단
>   사용하는 함수가 Promise 함수인지 판단하는 방법은 npm 참고한다.
>   ex) Sequelize  npm 설명 
>   Sequelize is a **promise-based** Node.js ORM tool for Postgres, MySQL, MariaDB, SQLite, Microsoft SQL Server, Amazon Redshift and Snowflake’s Data Cloud.
> - `.then()` , `.catch()` 할 때는 Promise 객체가 정의되지 않은 경우인거 같다. ( var, const 사용 x)
> - Promise 진행 흐름![출처 : MDN](C:\Users\User\Desktop\Study\TIL\image\Promise.JPG)[출처 : MDN]



#### async/await

---

async/await는 기존의 비동기 처리 방식인 콜백 함수와 프로미스의 단점을 보완하고 개발자가 읽기 좋은 코드를 작성할 수 있게 도와준다.

- async/await 기본 문법
  		

  ```javascript
  async function 함수명() {
  	await 비동기_처리_메서드_명();
  }
  ```

  먼저 함수 앞에 `async`라는 예약어를 붙이다.

  함수 내부에는 비동기 처리 코드 앞에 `await`를 붙인다.

  주의해야할 것은 비동기 처리 메서드가 꼭 프로미스 객체를 반환해야 await가 의도한 대로 동작한다는 것이다. 

  다음은 예시 코드이다.

  ```javascript
  function fetchUser() {
    var url = 'https://jsonplaceholder.typicode.com/users/1'
    return fetch(url).then(function(response) {
      return response.json();
    });
  }
  
  function fetchTodo() {
    var url = 'https://jsonplaceholder.typicode.com/todos/1';
    return fetch(url).then(function(response) {
      return response.json();
    });
  }
  ```

  ```javascript
  async function logTodoTitle() {
    var user = await fetchUser();
    if (user.id === 1) {
      var todo = await fetchTodo();
      console.log(todo.title); // delectus aut autem
    }
  }
  
  ```

  ```javascript
  await logTodoTile();
  ```

   [출처] https://joshua1988.github.io/web-development/javascript/js-async-await/
  
- async/await `.then` 
  예제 코드

  ```javascript
  passport.deserializeUser((id, done) => {
        await User.findOne({
          where: { id }
        })
        .then(user => done(null, user))
        .catch(err => done(err));
      });
  ```

- async/await  예외 처리

  async/await 에서 예외를 처리하는 방법은 try/catch이다. 

  async에서는 `catch {}` 를 사용하여 에러 처리를 한다.

  ```javascript
  async function logTodoTitle() {
    try {
      var user = await fetchUser();
      if (user.id === 1) {
        var todo = await fetchTodo();
        console.log(todo.title); // delectus aut autem
      }
    } catch (error) {
      console.log(error);
    }
  }
  ```

  위의 코드는 아래 try/catch를 보고난 이후에 다시 보도록 하자.



#### try/catch

---

- 문법

  ```javascript
  try {
  
    // 코드...
  
  } catch (err) {
  
    // 에러 핸들링
  
  }
  ```

  1. `try {...}` 안의 코드가 실행된다.
  2. 에러가 없으면, `try`  안의 코드가 끝가지 실행되고, `catch` 블록은 건너뛴다.
  3. 에러가 있다면, `try` 안의 코드 실행이 중단되고, `catch(err)` 블록으로 제어 흐름이 넘어간다. 
     변수 `err`는 무슨 일이 일어났는지에 대한 설명이 담긴 에러 객체를 포함한다.

- `err`
  err의 경우는 npm을 사용하여 만들어낸 결과 값인 경우 npm 설명에 err에 관한 정보가 기록되어 있다.
  단순한 에러가 아니라 경우 따른 대처를 하고 싶을 때 try/catch를 사용하는 것이 좋을 것 같다. 
  ex)

  ```javascript
  jwt.verify(token, 'shhhhh', function(err, decoded) {
    if (err) {
      /*
        err = {
          name: 'TokenExpiredError',
          message: 'jwt expired',
          expiredAt: 1408621000
        }
      */
    }
  });
  ```

  
